---
type: yml
auth:
  sign_key: jwt-secret

http_server:
  port: 8000

mysql:
  port: 3306  
  host: localhost
  username: root
  password: password
  db_name: gamedb

redis:
  port: 6379
  host: localhost
  db: 0
  password: ""

matching_service:
  waiting_timeout: "2m"
  
presence_service:
  presence_expiration_time: "60m"
  presence_prefix: "presence"

scheduler:
  match_waited_users_inerval_in_seconds: 30